spring:
  application:
    name: gateway-server
  profiles:
    active: dev  # IntelliJ'de local çalışırken dev profilini kullanacak

---

spring:
  config:
    activate:
      on-profile: dev
    import: "configserver:http://localhost:8989"  # IntelliJ için local adres

---

spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-server:8989"  # Docker içinden erişim
