

services:
  config-server:
    image: halitkalayci/turkcell-45-config-server
    ports:
      - "8989:8989"
  discovery-server:
    image: halitkalayci/tcell-45-discovery-server
    ports:
      - "8761:8761"
  gateway-server:
    image: halitkalayci/tcell-45-gateway-server
    ports:
      - "8888:8888"
    depends_on:
      - config-server
    environment:
      - CONFIG_URI=http://config-server:8989    #dockerın içinde başka bir containera işaret etmek istiyorsak composeda o containerın ismi yazılmalı ve sağdaki port
