version: "3.8"

networks:
  microservices-net:

services:
  # CONFIG SERVER
  config-server:
    image: meryemozevren/turkcell-45-config-server2
    container_name: config-server
    ports:
      - "8066:8989"
    networks:
      - microservices-net

  # DISCOVERY SERVER (EUREKA)
  discovery-server:
    image: meryemozevren/turkcell-45-discovery-server
    container_name: discovery-server
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    environment:
      - CONFIG_URI=http://config-server:8989
    networks:
      - microservices-net

  # GATEWAY SERVER
  gateway-server:
    image: meryemozevren/turkcell-45-gateway-server
    container_name: gateway-server
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8888:8888"
    environment:
      - CONFIG_URI=http://config-server:8989
      - EUREKA_URI=http://discovery-server:8761/eureka/
    networks:
      - microservices-net

  # POSTGRESQL
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  # PRODUCT SERVICE
  product-service:
    image: meryemozevren/turkcell-45-product-service
    container_name: product-service
    depends_on:
      - config-server
      - discovery-server
      - postgres
    ports:
      - "8080:8080"
    environment:
      - CONFIG_URI=http://config-server:8989
      - EUREKA_URI=http://discovery-server:8761/eureka/
    networks:
      - microservices-net

  # ORDER SERVICE
  order-service:
    image: meryemozevren/turkcell-45-order-service
    container_name: order-service
    depends_on:
      - config-server
      - discovery-server
      - postgres
    ports:
      - "8082:8082"
    environment:
      - CONFIG_URI=http://config-server:8989
      - EUREKA_URI=http://discovery-server:8761/eureka/
    networks:
      - microservices-net

  # CART SERVICE
  cart-service:
    image: meryemozevren/turkcell-45-cart-service
    container_name: cart-service
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8083:8083"
    environment:
      - CONFIG_URI=http://config-server:8989
      - EUREKA_URI=http://discovery-server:8761/eureka/
    networks:
      - microservices-net

  # PAYMENT SERVICE
  payment-service:
    image: meryemozevren/turkcell-45-payment-service
    container_name: payment-service
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8081:8081"
    environment:
      - CONFIG_URI=http://config-server:8989
      - EUREKA_URI=http://discovery-server:8761/eureka/
    networks:
      - microservices-net

volumes:
  postgres_data:
