# Sıfır bir makinede (FreeDOS) bu projeyi nasıl kurarım?
# işletim sistemi -> java -> maven -> proje -> run

# işletim sistemi -> java -> maven ✅

#SİNGLE STAGE -> ÖNERİLMEZ(IMAGE BOYUTU BÜYÜK)

#from yeni bir katamana başlaraken
FROM maven:3.9-eclipse-temurin-21

# -> proje -> run
WORKDIR /app

#sol nokta ana dizin, sağ nokta docker'daki işletim sistemi
COPY . .

RUN mvn dependency:purge-local-repository
#docker'da jar dosyası oluşturarak son halini alıp build etmesini sağlıyoruz
RUN mvn clean package -DskipTests

ENTRYPOINT ["java","-jar","target/config-server-0.0.1-SNAPSHOT.jar"]

#docker build -t tcell-config-server .  -> bu komutla oluşturmaya başlıyoruz
#docker run -d -p 8989:8989 tcell-config-server

docker hub a yükleme komutları
docker tag tcell-config-server2 halitkalayci/turkcell-45-config-server
docker push halitkalayci/turkcell-45-config-server