spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka/}

  cloud:
    stream:
      bindings:
        productCreated-in-0:
          destination: product-topic     # Aynı topic
          group: order-service-group     # Consumer
      kafka:
        binder:
          brokers: localhost:9094        # Kafka broker adresi
