spring:
  application:
    name: product-service

  # Varsayılan profil: dev
  profiles:
    active: dev

  # Config Server adresi (Docker ve Local ortamları ayrı ayrı tanımlanıyor)
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8066}

---

spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:${CONFIG_URI:http://config-server:8989}

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:${CONFIG_URI:http://localhost:8066}
