spring:
  application:
    name: product-service
  profiles:
    active: dev  # IntelliJ'de local çalışırken dev profilini kullanacak
---

spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-server:8989"  # Docker içinden erişim
