spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_URI:http://config-server:8989}

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:${CONFIG_URI:http://localhost:8989}
