spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8989"

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-server:8989"
