spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka/}

  cloud:
    stream:
      bindings:
        productCreated-out-0:  #StreamBridge içinde kullanılacak binding adı.
          destination: product-topic     # Kafka topic adı
      kafka:
        binder:
          brokers: kafka:9092        # Kafka broker adresi
