eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka/}
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
