spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1Mery/Gy4.5-microservices.git
          default-label: main
          search-paths:
            - configurations
            - configurations/{application}
          clone-on-start: true
          force-pull: true
 #konfigürasyonları çekeceği yeri belirtiyorum(github projem içindeki maim branchinde bulunan belirtilen dosyalar içinden)
server:
  port: 8989